### ISSUE TITLE
تغذیه ch340g

### ISSUE THREAD

**Issue by mehi79** [aKaReZa75/eBoard_ATMEGA328#3]
سلام مهندس خسته نباشید . ی سوالی داشتم راجب تغذیه ایسی usb به سریال . اگر ولتاژ تغذیه این ایسی رو 3.3 ولت بدیم مشکلی پیشش میاد ؟ چون دیتایی که داره میگیره از پورت کامپیوتر هست .
یک در خواست هم داشتم . اگر امکانش هست داخل ویدیو نحوه ایجاد pull request رو بگید .چون من از پروژه ها ( هم eboard و هم RCS ) fork میگیرم و تغییرات هم اعمال میکنم اما نمیتونم pull request بفرستم یعنی اصلا تغییرات من رو شناسایی نمیکنه و میگه تغییری برای مقایسه وجود نداره

**Comment by aKaReZa75** [comment]
سلام دوست عزیز، خیر مشکلی پیش نمیاد و میتونه کار کنه.
شما باید تغییراتی رو که توی سیستم خدتون اعمال کردین ( منظورم کامیت های هست) بعد ازون از دستور git push استفاده کنید که بیاد روی گیتهابتون، و بعد ازین دیگه اون میتونید پول ریکوئست بفرستین.
